public enum PeriodicTable{
//Atom(positive,negative),
    //deadly is considered if a human is exposed, anything that has to be "in large amounts" was not considered deadly

    Hydrogen(1, false),
    Helium(2, false),
    Lithium(3, true),
    Beryllium(4, true),
    Boron(5, false),
    Carbon(6, false),
    Nitrogen(7, false),
    Oxygen(8, false),
    Fluorine(9, true),
    Neon(10, false),
    Sodium(11, false),
    Magnesium(12, false),
    Aluminium(13, false),
    Silicon(14, false),
    Phosphorus(15, true),
    Sulfur(16, false),
    Chlorine(17, false), //consumption of chlorine is deadly, however exposure is not, in gaseous form it can be deadly
    Argon(18, false),
    Potassium(19, false),
    Calcium(20, false),
    Scandium(21, false),
    Titanium(22, false),
    Vanadium(23, false),
    Chromium(24, false),
    Manganese(25, false),
    Iron(26, false),
    Cobalt(27, false),
    Nickel(28, false),
    Copper(29, false),
    Zinc(30, false),
    Gallium(31, false),
    Germanium(32, false),
    Arsenic(33, true),
    Selenium(34, false),
    Bromine(35, true),
    Krypton(36, false),
    Rubidium(37, false), //is toxic but not deadly
    Strontium(38, true),
    Yttrium(39, false),
    Zirconium(40, false),
    Niobium(41, false), //not enough research to determine if truly toxic
    Molybdenum(42, false),
    Technetium(43, true),
    Ruthenium(44, true),
    Rhodium(45, true),
    Palladium(46, true),
    Silver(47, false),
    Cadmium(48, true),
    Indium(49, false),
    Tin(50, false),
    Antimony(51, false),//*
    Tellurium(52, false),
    Iodine(53, false),
    Xenon(54, false),
    Cesium(55, true),
    Barium(56, true),
    Lanthanum(57, false),
    Cerium(58, false),
    Praseodymium(59, false),
    Neodymium(60, false),
    Promethium(61, true),
    Samarium(62, false),
    Europium(63, false),
    Gadolinium(64, false),
    Terbium(65, false),
    Dysprosium(66, false),
    Holmium(67, true),
    Erbium(68, false),
    Thulium(69, false),
    Ytterbium(70, false),
    Lutetium(71, false),
    Hafnium(72, false),
    Tantalum(73, false),
    Tungsten(74, false),
    Rhenium(75, false),
    Osmium(76,false),
    Iridium(77, false),
    Platinum(78, false),
    Gold(78, false),
    Mercury(80, true),
    Thallium(81, true),
    Lead(82, true),
    Bismuth(83, false),
    Polonium(84, true),
    Astatine(85, true),
    Radon(86, false), //can be toxic, however not deadly by minor exposure

    //most elements from here down are toxic due to radioactivity
    Francium(87, true),
    Radium(88, true),
    Actinium(89, true),
    Thorium(90, true),
    Protactinium(91, true),
    Uranium(92, true),
    Neptunium(93, true),
    Plutonium(94, true),
    Americium(95, true),
    Curium(96, true),
    Berkelium(97, true),
    Californium(98, true),
    Einsteinium(99, true),
    Fermium(100, true),
    Mendelevium(101, true),
    Nobelium(102, true),
    Lawrencium(103, true),
    Rutherfordium(104, true),
    Dubnium(105, true),
    Seaborgium(106, true),
    Bohrium(107, true),
    Hassium(108, true),
    Meitnerium(109, true),
    Darmstadtium(110, true),
    Roentgenium(111, true),
    Copernicium(112, true),
    Nihonium(113, true),
    Flerovium(114, true),
    Moscovium(115, true),
    Livermorium(116, true),
    Tennessine(117, true),
    Oganesson(118, true);

    PeriodicTable(int atomicNum, boolean deadly) {
    }
}
